### ISSUE TITLE
1.5.0 break the compatibility

### ISSUE THREAD

**Issue by zcong** [dabapps/django-log-request-id#41]
I got this error for the new version of log-request-id
`    from log_request_id import local, NO_REQUEST_ID, OUTGOING_REQUEST_ID_HEADER_SETTING
ImportError: cannot import name NO_REQUEST_ID`

**Comment by j4mie** [comment]
Hi, thanks for letting us know about this.

Trying to understand your use case here - why are you importing that constant in your code?

We could just add a backwards compatibility shim so that will still work, but I wasn't expecting that would be something that users of the package would import themselves.
