### ISSUE TITLE
Add processing_time to log line

### ISSUE THREAD

**Issue by cornmander** [dabapps/django-log-request-id#7]
Would you be open to adding a `processing_time` metric to each log line? It would keep track of the time from `process_request` to `process_response`. I can implement it and send you a pull request.

**Comment by j4mie** [comment]
I'm not sure about this.. most platforms (eg Heroku) will give you the timing data from a component higher up the stack than the Django app (ie the router/proxy/load balancer).

If you really need it from the Django app itself, it would be trivial to write some timing middleware that sits just below `django-log-request-id` and just logs the time. This might be a good third party package, `django-log-request-time` or similar.

I think I'd prefer to keep this library simple. Feel free to try to persuade me though :)

**Comment by tomchristie** [comment]
> Feel free to try to persuade me though :)

Adopting my standard policy of proactively closing issues. I'd suggest then just reopening if later re-assessment is that you do want to pursue this.

**Comment by thenewguy** [comment]
@j4mie @tomchristie Any chance to reopen this?  It seems like this is the perfect place to log this since it is the first request / last response processor in the middleware stack.  Or perhaps add a hook to log the information?  Nginx/gunicorn output this and it would be nice to capture this time metric for comparison
