### ISSUE TITLE
Question: how is it better then simple process/thread ID logging

### ISSUE THREAD

**Issue by askaliuk** [dabapps/django-log-request-id#8]
Let's imagine that i don't use `X_REQUEST_ID` and `LOG_REQUESTS = True` features.
How this application is more useful than simple process/thread ID logging?
May be there some issues that I'm not aware of.

Example of simple thread/process ID logging:
```
'formatters': {
        'verbose': {
            'format': '%(levelname)s | %(asctime)s | %(name)s | %(process)d | %(thread)d | %(message)s'
        },
    },
```

Thank you.

**Comment by vangale** [comment]
Using the process / thread id works if you need the process or thread id in
your logs. This isn't the same as request id and, in fact, you might want
them in addition to request id.

The point of a request id is to have a unique id which you can search in
the logs to see all log messages generated from a single specific request.

This is different from a process id, thread id, ssl session id, session id,
etc. because those id's can be associated with thousands of requests a day
possibly including from different users. Also, they aren't guaranteed to be
unique in a cluster.

**Comment by askaliuk** [comment]
@vangale thank you for clarification
